; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
;monitor_speed = 57600


; CONFIGURACIÓN ESPECÍFICA PARA MONITOR SERIE
monitor_filters =
    direct
    esp32_exception_decoder
    time
monitor_dtr = 0
monitor_rts = 0
monitor_raw = no

; Librerías necesarias para el proyecto
lib_deps =
    esp32-camera
    SD_MMC

; Configuración de upload
;upload_port = /dev/ttyUSB0  ; Ajusta según tu puerto
upload_flags =
    --before=default_reset
    --after=hard_reset

; Flags de compilación (opcionales, pero recomendados para estabilidad)
; Deshabilitan el log por defecto del chip y liberan más recursos para la cámara
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_ARCH_ESP32
    -DBT_ENABLED
